let selectedBrand='';let searchList=null;const $=id=>document.getElementById(id);const wa=n=>'https://wa.me/918840725164?text='+encodeURIComponent('Hello R.S. Electronics, please share today\'s price and availability for '+n+'.');
function brandsList(){return [...new Set(products.map(p=>p.brand))]}
function renderBrands(){ $('brandsRow').innerHTML=brandsList().map(b=>`<button class="brand-pill ${selectedBrand===b?'selected':''}" onclick="setBrand('${b.replace(/'/g,"\\'")}')">${b}</button>`).join('') }
function visual(i,cls=''){let hue=(i*53)%360;return `<div class="device ${cls}" style="--h:${hue}"><span></span></div>`}
function card(p,i){let image=p.imageUrl&&p.imageUrl.trim()?`<img src="${p.imageUrl}" alt="${p.brand} ${p.name}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.parentElement.querySelector('.image-fallback').style.display='grid'">`:'';return `<article class="product"><span class="product-year">${p.year}</span><div class="product-image">${image}<div class="image-fallback" style="display:${image?'none':'grid'}">${visual(i)}</div></div><h3>${p.name}</h3><small>${p.brand} • ${p.variant}</small><div class="product-price">${p.price}</div><div class="card-row"><button class="details" onclick="details(${i})">Details</button><a class="official" href="${p.official}" target="_blank" rel="noopener">Official ↗</a><a class="wa-small" href="${wa(p.name)}" target="_blank">WA</a></div></article>`}
function renderProducts(){let q=($('search').value||'').toLowerCase().trim();let year=$('yearFilter').value;let list=searchList||products;let arr=list.filter(p=>(!selectedBrand||p.brand===selectedBrand)&&(!year||String(p.year)===year)&&(!q||(p.name+' '+p.brand+' '+p.variant+' '+p.year).toLowerCase().includes(q)));$('activeFilter').textContent=selectedBrand?`Filtered: ${selectedBrand} • ${arr.length} results`:q?`${arr.length} matching results`:'';$('products').innerHTML=arr.length?arr.map(p=>card(p,products.indexOf(p))).join(''):`<div class="empty">No model found. <a href="${wa('the phone you are looking for')}" target="_blank">Ask R.S. Electronics on WhatsApp →</a></div>`}
function setBrand(b){selectedBrand=selectedBrand===b?'':b;searchList=null;renderBrands();renderProducts();location.hash='phones'}
function doSearch(){searchList=null;renderProducts()}
function resetFilters(){selectedBrand='';searchList=null;$('search').value='';$('yearFilter').value='';renderBrands();renderProducts()}
function quickNeed(n){$('purpose').value=n;let arr=products.filter(p=>p.needs&&p.needs.includes(n)).slice(0,8);searchList=arr;selectedBrand='';renderBrands();renderProducts();document.querySelector('#phones').scrollIntoView({behavior:'smooth'})}
function latest(){let offset=0;function draw(){let arr=[0,1,2,3,4].map((_,n)=>products[(offset+n)%products.length]);$('latest').innerHTML=arr.map(p=>`<div class="latest-item"><div class="mini-device" style="--h:${(products.indexOf(p)*53)%360}"></div><div><b>${p.name}</b><small>${p.brand} • ${p.year}</small><em>${p.price}</em></div></div>`).join('');offset=(offset+1)%products.length}draw();setInterval(draw,2600)}
function options(){let o='<option value="">Select phone</option>'+products.map((p,i)=>`<option value="${i}">${p.name} — ${p.brand} (${p.variant})</option>`).join('');['c1','c2','c3'].forEach(id=>$(id).innerHTML=o)}
function compare(){let ids=['c1','c2','c3'].map(id=>$(id).value).filter(v=>v!=='');if(ids.length<2){$('comparison').innerHTML='<div class="empty">Select at least two phones to compare.</div>';return}let ps=ids.map(Number).map(i=>products[i]);$('comparison').innerHTML=`<table class="compare-table"><tr><th>Feature</th>${ps.map(p=>`<th>${p.name}</th>`).join('')}</tr><tr><td>Brand</td>${ps.map(p=>`<td>${p.brand}</td>`).join('')}</tr><tr><td>Year</td>${ps.map(p=>`<td>${p.year}</td>`).join('')}</tr><tr><td>Variant</td>${ps.map(p=>`<td>${p.variant}</td>`).join('')}</tr><tr><td>Price</td>${ps.map(p=>`<td><b>${p.price}</b></td>`).join('')}</tr><tr><td>Best for</td>${ps.map(p=>`<td>${(p.needs||[]).join(' • ')}</td>`).join('')}</tr></table>`}
function findPhone(){let n=$('purpose').value;if(!n){$('finderResult').textContent='Choose a priority first.';return}let arr=products.filter(p=>p.needs&&p.needs.includes(n)).slice(0,2);$('finderResult').innerHTML=arr.length?`Try <b>${arr.map(p=>p.name).join('</b> or <b>')}</b><br><a href="${wa(arr[0].name)}" target="_blank">Ask today's price →</a>`:'No exact match — ask the store.'}
function details(i){let p=products[i];$('modalContent').innerHTML=`<div class="detail-grid"><div>${p.imageUrl&&p.imageUrl.trim()?`<img class="detail-device" src="${p.imageUrl}" alt="${p.name}" onerror="this.replaceWith(document.createRange().createContextualFragment('${visual(i,'detail-device').replace(/'/g,"\\'")}'))">`:visual(i,'detail-device')}</div><div><span class="eyebrow">${p.brand} • ${p.year}</span><h2>${p.name}</h2><p>${p.variant}</p><h3>${p.price}</h3><p>Best for: ${(p.needs||[]).join(' • ')}</p><div class="hero-buttons"><a class="btn dark" href="${p.official}" target="_blank" rel="noopener">Official page ↗</a><a class="btn light" href="${wa(p.name)}" target="_blank">WhatsApp</a></div></div></div>`;$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
function openEMI(){alert('EMI estimate: send the phone model, price and preferred tenure to R.S. Electronics on WhatsApp for the latest available EMI options.');location.href=wa('EMI options')}
function toggleTheme(){document.body.classList.toggle('dark-mode');localStorage.setItem('rsTheme',document.body.classList.contains('dark-mode')?'dark':'light')}
if(localStorage.getItem('rsTheme')==='dark')document.body.classList.add('dark-mode');$('modelCount').textContent=products.length+'+';renderBrands();renderProducts();latest();options();
